packages:
  - packages/*
  - libs/*
  - apps/*

catalog:
  '@guiiai/logg': ^1.2.5
  '@unbird/result': ^1.1.1
  '@xsai-ext/providers-cloud': ^0.4.0-beta.9
  '@xsai-ext/providers-local': ^0.4.0-beta.9
  '@xsai/embed': ^0.4.0-beta.9
  '@xsai/tool': ^0.4.0-beta.9
  vue-sonner: ^2.0.9
  xsai: ^0.4.0-beta.9
  xsschema: ^0.4.0-beta.9

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - bufferutil
  - electron
  - electron-winstaller
  - es5-ext
  - esbuild
  - sharp
  - unrs-resolver
  - utf-8-validate
  - vue-demi
  - websocket
