packages:
  - packages/*
  - libs/*
  - apps/*

catalog:
  '@guiiai/logg': ^1.2.11
  '@unbird/result': ^1.1.1
  '@xsai-ext/providers-cloud': ^0.4.0-beta.12
  '@xsai-ext/providers-local': ^0.4.0-beta.12
  '@xsai/embed': ^0.4.0-beta.12
  '@xsai/tool': ^0.4.0-beta.12
  tsdown: ^0.18.2
  vue-sonner: ^2.0.9
  xsai: ^0.4.0-beta.12

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - bufferutil
  - core-js
  - electron
  - electron-winstaller
  - es5-ext
  - esbuild
  - protobufjs
  - sharp
  - unrs-resolver
  - utf-8-validate
  - vue-demi
  - websocket
